// <auto-generated />
using System;
using LibraryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("LibraryApi.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1452783-17f5-432e-823b-d963b3c02264"),
                            Author = "Robert Louis Stevenson",
                            Genre = "Adventure",
                            PublishedDate = new DateTime(1883, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Treasure Island"
                        },
                        new
                        {
                            Id = new Guid("7b41e4c2-6351-43e9-b734-b5a7418c96a0"),
                            Author = "Michael Crichton",
                            Genre = "Adventure",
                            PublishedDate = new DateTime(1990, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = new Guid("69badaa9-bdbc-4269-a3b4-c0f145ec4704"),
                            Author = "Eric Carle",
                            Genre = "Children",
                            PublishedDate = new DateTime(1969, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Very Hungry Caterpillar"
                        },
                        new
                        {
                            Id = new Guid("c4b38ac8-4923-4c8c-bf1b-c4f44d70fee8"),
                            Author = "Agatha Christie",
                            Genre = "Mystery",
                            PublishedDate = new DateTime(1934, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = new Guid("bfd63f97-b915-4edc-9a9f-90c13ea24e42"),
                            Author = "Jane Austen",
                            Genre = "Romance",
                            PublishedDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("cfd122fd-4dda-41c5-99e1-42da33699843"),
                            Author = "Colleen Hoover",
                            Genre = "Romance",
                            PublishedDate = new DateTime(2016, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "It Ends with Us"
                        },
                        new
                        {
                            Id = new Guid("a361cc74-8494-49b8-b716-176fb343c743"),
                            Author = "Douglas Adams",
                            Genre = "ScienceFiction",
                            PublishedDate = new DateTime(1987, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("2a4f5bd6-b5eb-42e2-8237-bcea33725094"),
                            Author = "George Orwell",
                            Genre = "ScienceFiction",
                            PublishedDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("23f07067-55d0-4a8a-bf75-a0a71cd2dcc9"),
                            Author = "Bram Stoker",
                            Genre = "Horror",
                            PublishedDate = new DateTime(1897, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = new Guid("fc2e239a-5fe0-44a8-9345-cc9ec80eb923"),
                            Author = "Stephen King",
                            Genre = "Horror",
                            PublishedDate = new DateTime(1977, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = new Guid("1c5a81a8-d678-4414-9fe8-c6eb601ad682"),
                            Author = "Stephen King",
                            Genre = "Horror",
                            PublishedDate = new DateTime(1985, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "It"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
